In [1]:
import torch

In [2]:
x=torch.arange(12)#行向量，从0到11
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [3]:
print(x.shape)#返回张量的形状

torch.Size([12])


In [4]:
print(x.numel())#返回张量的元素总数

12


In [5]:
X=x.reshape(3,4)#改变形状
#X=x.reshape(3,-1)
#X=x.reshape(-1,4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
print(torch.zeros(2,3,4))#创建全0张量，两通道，3行4列

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [7]:
print(torch.ones(2,3,4))#创建全1张量，两通道，3行4列

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [8]:
print(torch.randn(3,4))#创建3行4列的随机张量，服从标准正态分布

tensor([[-0.2383,  1.5807,  0.6367,  0.0719],
        [ 1.0828,  0.7026, -0.1680, -0.8941],
        [-0.7969, -0.7042, -0.5741,  0.4403]])


In [9]:
a=torch.tensor([[1,2,3,4],[5,6,7,8]])#直接创建张量确定数值
print(a)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [10]:
x=torch.tensor([1.0,2,3,4])
y=torch.tensor([5,6,7,8])
print(x+y)#加
print(x-y)#减
print(x*y)#乘
print(x/y)#除
print(x**y)#求幂

tensor([ 6.,  8., 10., 12.])
tensor([-4., -4., -4., -4.])
tensor([ 5., 12., 21., 32.])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04])


In [11]:
print(torch.exp(x))#e的x次方

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


In [12]:
X=torch.arange(12,dtype=torch.float32).reshape(3,4)
Y=torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(torch.cat((X,Y),dim=0))#按行进行连接
print(torch.cat((X,Y),dim=1))#按列进行链接

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
        [ 8.,  9., 10., 11.,  9., 10., 11., 12.]])


In [13]:
print(X==Y)#判断XY是否相等

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [14]:
print(X.sum())#对X的所有元素求和

tensor(66.)


In [15]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a,b)

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


In [16]:
print(a+b)#广播，a复制列，b复制行

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [17]:
X=torch.arange(12).reshape(3,4)
print(X[-1])#行最后一行
print(X[1:3])#第二行到第三行

tensor([ 8,  9, 10, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [18]:
X[2,2]=9#将第2行第3个元素改为9
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9,  9, 11]])


In [19]:
X[0:2, : ]=66#将第1行到第2行改为66
print(X)

tensor([[66, 66, 66, 66],
        [66, 66, 66, 66],
        [ 8,  9,  9, 11]])


In [20]:
before = id(Y)
Y=Y+X
print(id(Y)==before)

False


In [21]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[ : ]=X+Y
print('id(Z):',id(Z))

id(Z): 2551184223568
id(Z): 2551184223568


In [22]:
before=id(X)
X += Y
print(id(X)==before)

True


In [23]:
X=torch.arange(12).reshape(3,4)
A=X.numpy()
B=torch.tensor(A)
print(type(A),type(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [24]:
a=torch.tensor([3.5])
print(a,a.item(),float(a),int(a))

tensor([3.5000]) 3.5 3.5 3
