In [1]:
import torch

In [2]:
#标量
x=torch.tensor(2.0)
y=torch.tensor(3.0)
print(x+y,x-y,x*y,x/y,x**y)

tensor(5.) tensor(-1.) tensor(6.) tensor(0.6667) tensor(8.)


In [3]:
#向量
x=torch.arange(4)
print(x)

tensor([0, 1, 2, 3])


In [4]:
#索引
print(x[3])

tensor(3)


In [5]:
#长度
print(len(x))

4


In [6]:
#形状
print(x.shape)

torch.Size([4])


In [7]:
#矩阵
A=torch.arange(20).reshape(5,4)
print(A)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [8]:
#索引
print(A[2,3])

tensor(11)


In [9]:
#转置
print(A.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [10]:
#对称矩阵
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B==B.T)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [11]:
#张量
X=torch.arange(24).reshape(2,3,4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [12]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()#通过分配新内存，将A的一个副本分配到B
print(A,A+B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [13]:
#Hadamard积
print(A*B)

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [14]:
a=2
X=torch.arange(24).reshape(2,3,4)
print(a+X)
print(a*X)
print((a*X).shape)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])
torch.Size([2, 3, 4])


In [15]:
#元素总和
x=torch.arange(4,dtype=torch.float32)
print(x,x.sum())

tensor([0., 1., 2., 3.]) tensor(6.)


In [16]:
print(A.shape,A.sum())

torch.Size([5, 4]) tensor(190.)


In [17]:
#按列求和
A_sum_axis0=A.sum(axis=0)
print(A_sum_axis0,A_sum_axis0.shape)

tensor([40., 45., 50., 55.]) torch.Size([4])


In [18]:
#按列求和
A_sum_axis1=A.sum(axis=1)
print(A_sum_axis1,A_sum_axis1.shape)

tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


In [19]:
#沿着行和列进行求和
print(A.sum(axis=[0,1]))

tensor(190.)


In [20]:
#求平均值
print(A.mean())
print(A.sum()/A.numel())

tensor(9.5000)
tensor(9.5000)


In [21]:
#按行降低维度求平均值
print(A.mean(axis=0))
print(A.sum(axis=0)/A.numel())

tensor([ 8.,  9., 10., 11.])
tensor([2.0000, 2.2500, 2.5000, 2.7500])


In [22]:
#非降维求和
sum_A=A.sum(axis=1,keepdims=True)
print(sum_A)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [23]:
print(A/sum_A)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [24]:
print(A)
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [25]:
#点积
y=torch.ones(4,dtype=torch.float32)
print(x,y,torch.dot(x,y))
#逐元素求积，然后求和
print(torch.sum(x*y))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor(6.)
tensor(6.)


In [26]:
#矩阵向量积
print(A,A.shape)
print(x,x.shape)
print(torch.mv(A,x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) torch.Size([5, 4])
tensor([0., 1., 2., 3.]) torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])


In [27]:
#矩阵矩阵乘法
B=torch.ones(4,3)
print(torch.mm(A,B))

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [28]:
#L2范数
u=torch.tensor([3.0,-4.0])
print(torch.norm(u))

tensor(5.)


In [29]:
#L1范数
print(torch.abs(u).sum())

tensor(7.)


In [30]:
#范数
print(torch.norm(torch.ones(4,9)))

tensor(6.)
