In [1]:
import torch

In [2]:
x=torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


In [3]:
x.requires_grad_(True)#等价于x=torch.arange(4.0,requires_grad=True)
print(x.grad)#默认值是None

None


In [4]:
y=2*torch.dot(x,x)
print(y)

tensor(28., grad_fn=<MulBackward0>)


In [5]:
#反向传播
y.backward()
print(x.grad)

tensor([ 0.,  4.,  8., 12.])


In [6]:
print(x.grad==4*x)

tensor([True, True, True, True])


In [7]:
#在默认情况下，pytorch会累计梯度，需要清楚之前的值
x.grad.zero_()
y=x.sum()
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


In [8]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
print(x.grad)

tensor([0., 2., 4., 6.])


In [9]:
#分离计算
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
print(x.grad==u)

tensor([True, True, True, True])


In [10]:
x.grad.zero_()
y.sum().backward()
print(x.grad==2*x)

tensor([True, True, True, True])


In [11]:
#Python控制流的梯度计算
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

In [12]:
a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()
print(a.grad)
print(a.grad==d/a)

tensor(1024.)
tensor(True)
