In [1]:
import numpy as np

In [2]:
#整数型数组
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
#整数型数组 ——> 浮点型数组
arr2=arr1.astype(float)
print(arr2)

[1. 2. 3.]


In [4]:
#浮点型数组 ——> 整数型数组
arr3=arr2.astype(int)
print(arr3)

[1 2 3]


In [5]:
#整数型数组
arr=np.array( [1, 2, 3] )
print(arr)

[1 2 3]


In [6]:
#整数型数组与浮点数做运算
print(arr+0.0)
print(arr*1.0)

[1. 2. 3.]
[1. 2. 3.]


In [7]:
#整数型数组遇到除法（即便是除以整数）
print( arr / 1 )

[1. 2. 3.]


In [8]:
# 整数型数组与浮点型数组做运算
int_arr = np.array( [1, 2, 3] )
float_arr = np.array( [1.0, 2, 3] )
print( int_arr + float_arr )

[2. 4. 6.]


In [9]:
arr1=np.ones(3)#传入形状3
print(arr1)#造出一维数组

[1. 1. 1.]


In [10]:
arr2=np.ones((2,3))#传入形状(2,3)
print(arr2)#造出二维数组

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr3 = np.ones((2,3,4))#传入形状(2,3,4)
print(arr3) # 造出三维数组

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
print(arr1.shape)#查看形状
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 3, 4)


In [13]:
#将一维数组升级为二维数组
arr1=np.arange(10)
print(arr1)
arr2=arr1.reshape(2,-1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
#将二维数组降级为一维数组
arr2=np.arange(10).reshape(2,5)
print(arr2)
arr1=arr2.reshape(-1)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
#创建一维数组--向量
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [16]:
#创建二维数组--行矩阵
arr2=np.array([[1,2,3]])
print(arr2)

[[1 2 3]]


In [17]:
#创建二维数组--行矩阵
arr2=np.array([[1],[2],[3]])
print(arr2)

[[1]
 [2]
 [3]]


In [18]:
#创建二维数组--矩阵
arr4=np.array([[1,2,3],[4,5,6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [19]:
#递增数组
arr1=np.arange(10)#从0开始到10之前结束
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
#递增数组
arr2=np.arange(10,20)#从10开始到20之前结束
print(arr2)

[10 11 12 13 14 15 16 17 18 19]


In [21]:
#递增数组
arr3=np.arange(1,21,2)#从1开始到21之前结束步长为2
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19]


In [22]:
#全0数组
arr1=np.zeros(3)#形状为3的向量
print(arr1)

[0. 0. 0.]


In [23]:
#全1数组
arr2=np.ones((1,3))#形状为(1,3)的矩阵
print(arr2)

[[1. 1. 1.]]


In [24]:
#全3.14数组
arr3=3.14*np.ones((2,3))#形状为3.14的数组
print(arr3)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [25]:
#0-1均匀分布的浮点型数组
arr1=np.random.random(5)#形状为5的数组
print(arr1)

[0.74703651 0.20472958 0.02796648 0.78693292 0.97039443]


In [26]:
#60-100均匀分布的(3,3)浮点型数组
arr1=(100-60)*np.random.random((3,3))+60#形状为5的数组
print(arr1)

[[99.50446452 79.86161164 67.65492635]
 [65.80754958 96.105766   87.11926594]
 [61.60032011 98.44499965 63.38058459]]


In [27]:
#整数型随机数组
arr2=np.random.randint(10,100,(1,15))#形状为(1,15)的矩阵
print(arr2)

[[15 70 41 37 69 41 77 47 95 14 63 52 53 30 36]]


In [28]:
#服从正态分布的随机数组
arr3=np.random.normal(0,1,(2,3))#形状为(2,3)的数组,均值0，标准差1
print(arr3)

[[ 1.16670314  1.21288538  0.80657064]
 [-1.77490539 -0.47232555 -0.55221945]]


In [29]:
#服从正态分布的随机数组
arr3=np.random.randn(2,3)#形状为(2,3)的数组,默认均值0，标准差1
print(arr3)

[[-0.01993256  1.29396477 -0.17005311]
 [ 0.30009513 -0.77470541  0.30691894]]


In [30]:
#创建向量
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [31]:
#访问元素
print(arr1[3])#正向访问
print(arr1[-1])#倒着访问

4
9


In [32]:
#修改数组元素
arr1[3]=100
print(arr1)

[  1   2   3 100   5   6   7   8   9]


In [33]:
#创建矩阵
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [34]:
#访问元素
print(arr2[0,2])
print(arr2[1,-2])

3
5


In [35]:
#修改元素
arr2[1,1]=100.9#截断！！！！！！！！！！！！！！！
print(arr2)

[[  1   2   3]
 [  4 100   6]]


In [36]:
# 创建向量
arr1 = np.arange(0,90,10)
print(arr1)

[ 0 10 20 30 40 50 60 70 80]


In [37]:
# 花式索引
print( arr1[ [0,2] ] )

[ 0 20]


In [38]:
# 创建矩阵
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [39]:
# 花式索引
print( arr2[ [0,1] , [0,1] ] )
print( arr2[ [0,1,2] , [2,1,0] ] )

[1 6]
[3 6 9]


In [40]:
# 修改数组元素
arr2[ [0,1,2,3] , [3,2,1,0] ] = 100
print(arr2)

[[  1   2   3 100]
 [  5   6 100   8]
 [  9 100  11  12]
 [100  14  15  16]]


In [41]:
arr1 = np.arange(10)

In [42]:
print( arr1 )
print( arr1[ 1 : 4 ] ) # 从索引[1]开始，切到索引[4]之前
print( arr1[ 1 : ] ) # 从索引[1]开始，切到结尾
print( arr1[ : 4 ] ) # 从数组开头开始，切到索引[4]之前

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3]


In [43]:
print( arr1 ) 
print( arr1[ 2 : -2 ] ) # 切除开头 2 个和结尾 2 个
print( arr1[ 2 : ] ) # 切除开头 2 个
print( arr1[ : -2 ] ) # 切除结尾 2 个

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7]


In [44]:
print( arr1 ) 
print( arr1[ : : 2 ] ) # 每 2 个元素采样一次
print( arr1[ : : 3 ] ) # 每 3 个元素采样一次
print( arr1[ 1 : -1 : 2 ] ) # 切除一头一尾后，每 2 个元素采样一次

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[1 3 5 7]


In [45]:
arr2 = np.arange(1,21).reshape(4,5)
print( arr2 )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [46]:
print( arr2[ 1:3 , 1:-1 ] ) # 矩阵切片初体验

[[ 7  8  9]
 [12 13 14]]


In [47]:
print( arr2[ ::3 , ::2 ] ) # 跳跃采样

[[ 1  3  5]
 [16 18 20]]


In [48]:
print( arr2[ 2 , : ] ) # 提取第 2 行

[11 12 13 14 15]


In [49]:
print( arr2[ 1:3 , : ] ) # 提取 1 至 2 行

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [51]:
print( arr2[ 2 , : ] ) # 规范的提取行
print( arr2[2] ) # 简便的提取行

[11 12 13 14 15]
[11 12 13 14 15]


In [52]:
arr4 = np.arange(1,21).reshape(4,5)
print( arr4 )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [53]:
print( arr4[ : , 2 ] ) # 提取第 2 列（注意，输出的是向量）

[ 3  8 13 18]


In [54]:
print( arr4[ : , 1:3 ] ) # 提取 1 至 2 列

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]


In [56]:
cut=arr4[ : , 2 ]
cut=cut.reshape((-1,1))
print(cut)

[[ 3]
 [ 8]
 [13]
 [18]]


In [57]:
arr = np.arange(10) # 创建原数组 arr
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
cut = arr[ : 3 ] # 创建 arr 的切片 cut
print(cut)

[0 1 2]


In [59]:
cut[0] = 100 # 对切片的数值进行修改
print(cut)

[100   1   2]


In [60]:
 print(arr) # 原数组也被修改

[100   1   2   3   4   5   6   7   8   9]


In [61]:
arr = np.arange(10) # 创建一个 0 到 10 的向量 arr
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
copy = arr[ : 3 ] .copy() # 创建 arr 的拷贝切片
print(copy)

[0 1 2]


In [65]:
copy [0] = 100 # 对拷贝切片的数值进行修改
print(copy)

[100   1   2]


In [66]:
print(arr) # 原数组不为所动

[0 1 2 3 4 5 6 7 8 9]


In [67]:
arr1 = np.arange(10) # 创建一个 0 到 10 的数组变量 arr
print(arr1)
arr2 = arr1 # 把数组 1 赋值给另一个数组 2
print(arr2)
arr2[0] = 100 # 修改数组 2
print(arr2)
print(arr1) # 原数组也被修改

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [68]:
arr1 = np.arange(10) # 创建一个 0 到 10 的数组变量 arr
print(arr1)
arr2 = arr1.copy() # 把数组 1 的拷贝赋值给另一个数组 2
print(arr2)
arr2[0] = 100 # 修改数组 2
print(arr2)
print(arr1) # 查看数组 1

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]


In [69]:
arr1 = np.arange(1,4) # 创建向量
print(arr1)
arr2 = arr1.reshape( (1,-1) ) # 升级为矩阵
print(arr2)
arr3 = arr2.T # 行矩阵的转置
print(arr3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [70]:
arr1 = np.arange(3).reshape(3,1) # 创建列矩阵
print(arr1)
arr2 = arr1.T # 列矩阵的转置
print(arr2) # 结果为行矩阵

[[0]
 [1]
 [2]]
[[0 1 2]]


In [71]:
arr1 = np.arange(4).reshape(2,2) # 创建矩阵
print(arr1)
arr2 = arr1.T # 矩阵的转置
print(arr2)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [72]:
 # 创建向量
arr1 = np.arange(10)
print( arr1 )
 # 翻转向量
arr_ud = np.flipud(arr1)
print( arr_ud )

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [73]:
# 创建矩阵
arr2 = np.arange(1,21).reshape(4,5) 
print( arr2 )
# 左右翻转
arr_lr = np.fliplr(arr2)
print( arr_lr )
# 上下翻转
arr_ud = np.flipud(arr2)
print( arr_ud )

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]]
[[16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [74]:
# 创建向量 1
arr1 = np.array( [1,2,3] )
print(arr1)
# 创建向量 2
arr2 = np.array( [4,5,6] )
print(arr2)
 # 拼接
arr3 = np.concatenate( [arr1,arr2] )
print(arr3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [75]:
 # 创建数组 1
arr1 = np.array( [[1,2,3],[ 4,5,6]] )
print(arr1)
# 创建数组 2
arr2 = np.array( [[7,8,9],[10,11,12]] )
print(arr2)
# 按第一个维度（行）拼接
arr3 = np.concatenate( [arr1,arr2] ) # 默认参数 axis=0
print(arr3)
# 按第二个维度（列）拼接
arr4 = np.concatenate( [arr1,arr2] ,axis=1 )
print(arr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [76]:
# 创建向量
arr = np.arange(10,100,10)
print(arr)
# 分裂数组
arr1,arr2,arr3 = np.split( arr , [2,8] )
print(arr1)
print(arr2)
print(arr3)

[10 20 30 40 50 60 70 80 90]
[10 20]
[30 40 50 60 70 80]
[90]


In [77]:
# 创建矩阵
arr = np.arange(1,9).reshape(2,4)
print(arr)
# 按第一个维度（行）分裂
arr1,arr2 = np.split(arr,[1]) # 默认参数 axis=0
print(arr1 , '\n\n' , arr2) # 注意输出的是矩阵
 # 按第二个维度（列）分裂
arr1,arr2,arr3 = np.split( arr , [1,3] , axis=1 )
print( arr1 , '\n\n' , arr2 , '\n\n' , arr3 )

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]] 

 [[5 6 7 8]]
[[1]
 [5]] 

 [[2 3]
 [6 7]] 

 [[4]
 [8]]


In [78]:
# 创建矩阵
arr = np.arange(1,9).reshape(2,4)
print( arr )

[[1 2 3 4]
 [5 6 7 8]]


In [79]:
print( arr + 10 ) # 加法

[[11 12 13 14]
 [15 16 17 18]]


In [80]:
 print( arr - 10 ) # 减法

[[-9 -8 -7 -6]
 [-5 -4 -3 -2]]


In [81]:
print( arr * 10 ) # 乘法

[[10 20 30 40]
 [50 60 70 80]]


In [82]:
print( arr / 10 ) # 除法

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]]


In [83]:
print( arr ** 2) # 平方

[[ 1  4  9 16]
 [25 36 49 64]]


In [84]:
print( arr // 6) # 取整

[[0 0 0 0]
 [0 1 1 1]]


In [85]:
print( arr % 6) # 取余

[[1 2 3 4]
 [5 0 1 2]]


In [86]:
 # 创建矩阵
arr1 = np.arange(-1,-9,-1).reshape(2,4)
arr2 = -arr1
print( arr1 )
print( arr2 )

[[-1 -2 -3 -4]
 [-5 -6 -7 -8]]
[[1 2 3 4]
 [5 6 7 8]]


In [87]:
print( arr1 + arr2 ) # 加法

[[0 0 0 0]
 [0 0 0 0]]


In [88]:
print( arr1 - arr2 ) # 减法

[[ -2  -4  -6  -8]
 [-10 -12 -14 -16]]


In [89]:
print( arr1 * arr2 ) # 乘法

[[ -1  -4  -9 -16]
 [-25 -36 -49 -64]]


In [90]:
print( arr1 / arr2 ) # 除法

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]


In [91]:
print( arr1 ** arr2) # 幂方

[[      -1        4      -27      256]
 [   -3125    46656  -823543 16777216]]


In [92]:
# 向量
arr1 = np.array([-100,0,100])
print(arr1)
 # 矩阵
arr2 = np.random.random( (10,3) )
print(arr2)
# 广播
print(arr1*arr2)

[-100    0  100]
[[0.67271998 0.18215338 0.82579671]
 [0.12142238 0.78899307 0.06819022]
 [0.12791703 0.4161829  0.06204379]
 [0.22754436 0.22125902 0.52198402]
 [0.08035786 0.99496918 0.35138574]
 [0.20391139 0.45874981 0.79668628]
 [0.5165557  0.57441256 0.82127507]
 [0.40216731 0.3374826  0.10415014]
 [0.94341284 0.04785006 0.17262409]
 [0.34332042 0.17543338 0.05044508]]
[[-67.271998     0.          82.57967112]
 [-12.1422375    0.           6.81902158]
 [-12.79170307   0.           6.20437859]
 [-22.75443557   0.          52.19840225]
 [ -8.03578589   0.          35.13857383]
 [-20.39113853   0.          79.66862848]
 [-51.65556996   0.          82.12750719]
 [-40.21673068   0.          10.41501422]
 [-94.34128358   0.          17.26240927]
 [-34.33204236   0.           5.04450841]]


In [93]:
# 列矩阵
arr1 = np.arange(3).reshape(3,1)
print(arr1)
# 矩阵
arr2 = np.ones( (3,5) )
print(arr2)
# 广播
print(arr1*arr2)

[[0]
 [1]
 [2]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]


In [94]:
# 向量
arr1 = np.arange(3)
print(arr1)
# 列矩阵
arr2 = np.arange(3).reshape(3,1)
print(arr2)
 # 广播
print(arr1*arr2)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]


In [95]:
# 创建向量
arr1 = np.arange(5)
arr2 = np.arange(5)
print(arr1)
print(arr2)
 # 矩阵乘积
print( np.dot(arr1,arr2) )

[0 1 2 3 4]
[0 1 2 3 4]
30


In [96]:
 # 创建数组
arr1 = np.arange(5)
arr2 = np.arange(15).reshape(5,3)
print(arr1)
print(arr2)
 # 矩阵乘积
print( np.dot(arr1,arr2) )


[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 90 100 110]


In [97]:
# 创建数组
arr1 = np.arange(15).reshape(3,5)
arr2 = np.arange(5)
print(arr1)
print(arr2)
 # 矩阵乘积
print( np.dot(arr1,arr2) )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[ 30  80 130]


In [98]:
 # 创建数组 1
arr1 = np.arange(10).reshape(5,2)
print(arr1)
 # 创建数组 2
arr2 = np.arange(16).reshape(2,8)
print(arr2)
 # 矩阵乘积
print( np.dot(arr1,arr2) )

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[  8   9  10  11  12  13  14  15]
 [ 24  29  34  39  44  49  54  59]
 [ 40  49  58  67  76  85  94 103]
 [ 56  69  82  95 108 121 134 147]
 [ 72  89 106 123 140 157 174 191]]


In [99]:
 # 绝对值函数
arr_v = np.array( [-10, 0, 10] )
abs_v = np.abs(arr_v)
print( '原数组是：' , arr_v )
print( '绝对值是：' , abs_v )

原数组是： [-10   0  10]
绝对值是： [10  0 10]


In [100]:
 # 三角函数
theta = np.arange(3) * np.pi / 2
sin_v = np.sin(theta)
cos_v = np.cos(theta)
tan_v = np.tan(theta)
print( '原数组是：' , theta )
print( '正弦值是：' , sin_v )
print( '余弦值是：' , cos_v )
print( '正切值是：' , tan_v )

原数组是： [0.         1.57079633 3.14159265]
正弦值是： [0.0000000e+00 1.0000000e+00 1.2246468e-16]
余弦值是： [ 1.000000e+00  6.123234e-17 -1.000000e+00]
正切值是： [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [101]:
 # 指数函数
x = np.arange(1,4)
print( 'x =' , x )
print( 'e^x =' , np.exp(x) )
print( '2^x =' , 2**x )
print( '10^x = ' , 10**x )

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2 4 8]
10^x =  [  10  100 1000]


In [102]:
# 对数函数
x = np.array( [1,10,100,1000] )
print( 'x =' , x )
print( 'ln(x) =' , np.log(x) )
print( 'log2(x) =' , np.log(x) / np.log(2) )
print( 'log10(x) =' , np.log(x) / np.log(10) )

x = [   1   10  100 1000]
ln(x) = [0.         2.30258509 4.60517019 6.90775528]
log2(x) = [0.         3.32192809 6.64385619 9.96578428]
log10(x) = [0. 1. 2. 3.]


In [103]:
 # 最大值函数 np.max( )与最小值函数 np.min( )
arr = np.random.random((2,3))
print( arr )
print( '按维度一求最大值：' , np.max(arr,axis=0) )
print( '按维度二求最大值：' , np.max(arr,axis=1) )
print( '整体求最大值：' , np.max(arr) )

[[0.5000897  0.89956061 0.273812  ]
 [0.95217016 0.23106834 0.82784374]]
按维度一求最大值： [0.95217016 0.89956061 0.82784374]
按维度二求最大值： [0.89956061 0.95217016]
整体求最大值： 0.9521701564399846


In [104]:
 # 求和函数 np.sum( )与求积函数 np.prod( )
arr = np.arange(10).reshape(2,5)
print( arr )
print( '按维度一求和：' , np.sum(arr,axis=0) )
print( '按维度二求和：' , np.sum(arr,axis=1) )
print( '整体求和：' , np.sum(arr) )

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求和： [ 5  7  9 11 13]
按维度二求和： [10 35]
整体求和： 45


In [105]:
# 均值函数 np.mean( )与标准差函数 np.std( )
arr = np.arange(10).reshape(2,5)
print( arr )
print( '按维度一求平均：' , np.mean(arr,axis=0) )
print( '按维度二求平均：' , np.mean(arr,axis=1) )
print( '整体求平均：' , np.mean(arr) )

[[0 1 2 3 4]
 [5 6 7 8 9]]
按维度一求平均： [2.5 3.5 4.5 5.5 6.5]
按维度二求平均： [2. 7.]
整体求平均： 4.5


In [106]:
# 创建数组
arr = np.arange(1,7).reshape(2,3)
print(arr)
# 数组与数字作比较
print( arr >= 4 )

[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]


In [107]:
# 创建同维数组
arr1 = np.arange(1,6)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)
 # 同维度数组作比较
print( arr1 > arr2)

[1 2 3 4 5]
[5 4 3 2 1]
[False False False  True  True]


In [108]:
# 创建数组
arr = np.arange(1,10)
print(arr)
# 多个条件
print( (arr < 4) | (arr > 6) )

[1 2 3 4 5 6 7 8 9]
[ True  True  True False False False  True  True  True]


In [109]:
# 创建一个形状为 10000 的标准正态分布数组
arr = np.random.normal( 0,1,10000 )
# 统计该分布中绝对值小于 1 的元素个数
num = np.sum( np.abs(arr) < 1 ) 
print( num )

6895


In [110]:
# 创建同维数组
arr1 = np.arange(1,10)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)
# 统计这两个数组里是否有共同元素
print( np.any( arr1 == arr2 ) )

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
True


In [111]:
 # 模拟英语六级的成绩，创建 100000 个样本
arr = np.random.normal( 500,70,100000 )
 # 判断是否所有考生的分数都高于 250
print( np.all( arr > 250 ) )

False


In [112]:
# 创建数组
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [113]:
# 数组与数字作比较
print( arr > 4 )

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [114]:
# 筛选出 arr > 4 的元素
print( arr[ arr > 4 ] )

[ 5  6  7  8  9 10 11 12]


In [115]:
 # 创建同维数组
arr1 = np.arange(1,10)
arr2 = np.flipud(arr1)
print(arr1)
print(arr2)
# 同维度数组作比较
print( arr1 > arr2)
# 筛选出 arr1 > arr2 位置上的元素
print( arr1[ arr1 > arr2 ] )
print( arr2[ arr1 > arr2 ] )

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[False False False False False  True  True  True  True]
[6 7 8 9]
[4 3 2 1]


In [116]:
# 模拟英语六级成绩的随机数组，取 10000 个样本
arr = np.random.normal( 500,70,1000 )
# 找出六级成绩超过 650 的元素所在位置
print( np.where( arr > 650 ) )
# 找出六级成绩最高分的元素所在位置
print( np.where( arr == np.max(arr) ) )

(array([131, 176, 282, 470, 481, 493, 531, 638, 859, 874, 881, 925, 982],
      dtype=int64),)
(array([493], dtype=int64),)
