In [1]:
import pandas as pd

In [2]:
#创建字典
dict_v={'a':0,'b':0.25,'c':0.5,'d':0.75,'e':1}

In [3]:
#用字典创建对象
sr=pd.Series(dict_v)
sr

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [4]:
#先定义键与值
v=[0,0.25,0.5,0.75,1]
k=['a','b','c','d','e']

In [5]:
#用列表创建对象
sr=pd.Series(v,index=k)
sr

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [6]:
import numpy as np
import pandas as pd

In [7]:
# 用数组创建 sr
v = np.array( [ 53, 64, 72, 82 ] )
k = ['1 号', '2 号', '3 号', '4 号']
sr = pd.Series( v, index=k )
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int32

In [8]:
# 查看 values 属性
sr.values

array([53, 64, 72, 82])

In [9]:
# 查看 index 属性
sr.index

Index(['1 号', '2 号', '3 号', '4 号'], dtype='object')

In [10]:
import pandas as pd
import torch

In [11]:
#用张量创建sr
v=torch.tensor([53,64,72,82])
k=['1号','2号','3号','4号']
sr=pd.Series(v,index=k)
sr

1号    53
2号    64
3号    72
4号    82
dtype: int64

In [12]:
#查看values的属性
sr.values

array([53, 64, 72, 82], dtype=int64)

In [13]:
#创建sr1,各个病人的年龄
v1=[53,64,72,82]
i=['1号','2号','3号','4号']
sr1=pd.Series(v1,index=i)
sr1

1号    53
2号    64
3号    72
4号    82
dtype: int64

In [14]:
#创建sr2，各个病人的性别
v2=['女','男','男','女']
i=['1号','2号','3号','4号']
sr2=pd.Series(v2,index=i)
sr2

1号    女
2号    男
3号    男
4号    女
dtype: object

In [15]:
#创建df对象
df=pd.DataFrame({'年龄':sr1,'性别':sr2})
df

年龄 性别
1号  53  女
2号  64  男
3号  72  男
4号  82  女

In [16]:
#设定键值
v=np.array([[53,'女'],[64,'男'],[72,'男'],[82,'女']])
i=['1号','2号','3号','4号']
c=['年龄','性别']
#数组创建法
df=pd.DataFrame(v,index=i,columns=c)
df

年龄 性别
1号  53  女
2号  64  男
3号  72  男
4号  82  女

In [17]:
#查看values属性
df.values

array([['53', '女'],
       ['64', '男'],
       ['72', '男'],
       ['82', '女']], dtype=object)

In [18]:
# 查看 index 属性
df.index

Index(['1号', '2号', '3号', '4号'], dtype='object')

In [19]:
 # 查看 columns 属性
df.columns

Index(['年龄', '性别'], dtype='object')

In [20]:
# 提取完整的数组
arr = df.values
print(arr)

[['53' '女']
 ['64' '男']
 ['72' '男']
 ['82' '女']]


In [21]:
# 提取第[0]列，并转化为一个整数型数组
arr = arr[:,0].astype(int)
print(arr)

[53 64 72 82]


In [22]:
# 创建 sr
v = [ 53, 64, 72, 82 ]
k = ['1 号', '2 号', '3 号', '4 号']
sr = pd.Series( v, index=k )
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [23]:
# 访问元素
sr.loc[ '3 号' ]

72

In [24]:
# 访问元素
sr.iloc[ 2 ]

72

In [25]:
# 花式索引
sr.loc[ [ '1 号', '3 号' ] ]

1 号    53
3 号    72
dtype: int64

In [26]:
# 花式索引
sr.iloc[ [ 0, 2 ] ]

1 号    53
3 号    72
dtype: int64

In [27]:
 # 修改元素
sr.loc[ '3 号' ] = 100
sr

1 号     53
2 号     64
3 号    100
4 号     82
dtype: int64

In [28]:
# 修改元素
sr.iloc[ 2 ] = 100
sr

1 号     53
2 号     64
3 号    100
4 号     82
dtype: int64

In [29]:
# 创建 sr
v = [ 53, 64, 72, 82 ]
k = ['1 号', '2 号', '3 号', '4 号']
sr = pd.Series( v, index=k )
sr

1 号    53
2 号    64
3 号    72
4 号    82
dtype: int64

In [30]:
 # 访问切片
sr.loc[ '1 号':'3 号' ]

1 号    53
2 号    64
3 号    72
dtype: int64

In [31]:
# 访问切片
sr.iloc[ 0:3 ]

1 号    53
2 号    64
3 号    72
dtype: int64

In [32]:
# 切片仅是视图
cut = sr.loc[ '1 号':'3 号' ]
cut.loc['1 号'] = 100
sr

1 号    100
2 号     64
3 号     72
4 号     82
dtype: int64

In [33]:
# 切片仅是视图
cut = sr.iloc[ 0:3 ]
cut.iloc[0] = 100
sr

1 号    100
2 号     64
3 号     72
4 号     82
dtype: int64

In [34]:
# 对象赋值仅是绑定
cut = sr
cut.loc['3 号'] = 200
sr

1 号    100
2 号     64
3 号    200
4 号     82
dtype: int64

In [35]:
 # 对象赋值仅是绑定
cut = sr
cut.iloc[2] = 200
sr

1 号    100
2 号     64
3 号    200
4 号     82
dtype: int64

In [36]:
 # 字典创建法
i = [ '1 号', '2 号', '3 号', '4 号' ]
v1 = [ 53, 64, 72, 82 ]
v2 = [ '女', '男', '男', '女' ]
sr1 = pd.Series( v1, index=i )
sr2 = pd.Series( v2, index=i )
df = pd.DataFrame( { '年龄':sr1, '性别':sr2 } )
df

年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

In [37]:
 # 访问元素
df.loc[ '1 号', '年龄' ]

53

In [38]:
 # 访问元素
df.iloc[ 0, 0 ]

53

In [39]:
# 花式索引
df.loc[ ['1 号', '3 号'] , ['性别','年龄'] ]

性别  年龄
1 号  女  53
3 号  男  72

In [40]:
# 花式索引
df.iloc[ [0,2], [1,0] ]

性别  年龄
1 号  女  53
3 号  男  72

In [41]:
 # 修改元素
df.loc[ '3 号', '年龄' ] = 100
df

年龄 性别
1 号   53  女
2 号   64  男
3 号  100  男
4 号   82  女

In [42]:
# 修改元素
df.iloc[ 2, 0 ] = 100
df

年龄 性别
1 号   53  女
2 号   64  男
3 号  100  男
4 号   82  女

In [43]:
 # 数组创建法
v = [ [53, '女'], [64, '男'], [72, '男'], [82, '女'] ]
i = [ '1 号', '2 号', '3 号', '4 号' ]
c = [ '年龄', '性别' ]
df = pd.DataFrame( v, index=i, columns=c )
df

年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

In [44]:
# 切片
df.loc[ '1 号':'3 号' , '年龄' ]

1 号    53
2 号    64
3 号    72
Name: 年龄, dtype: int64

In [45]:
# 切片
df.iloc[ 0:3 , 1 ]

1 号    女
2 号    男
3 号    男
Name: 性别, dtype: object

In [46]:
# 提取二维对象的行
df.loc[ '3 号' , : ]

年龄    72
性别     男
Name: 3 号, dtype: object

In [47]:
# 提取二维对象的行
df.iloc[ 2 , : ]

年龄    72
性别     男
Name: 3 号, dtype: object

In [48]:
# 提取矩阵对象的列
df.loc[ : , '年龄' ]

1 号    53
2 号    64
3 号    72
4 号    82
Name: 年龄, dtype: int64

In [49]:
# 提取矩阵对象的列
df.iloc[ : , 0 ]

1 号    53
2 号    64
3 号    72
4 号    82
Name: 年龄, dtype: int64

In [50]:
 # 创建畸形 df
v = [ [53, 64, 72, 82], [ '女', '男', '男', '女' ] ]
i = [ '年龄', '性别' ]
c = [ '1 号', '2 号', '3 号', '4 号' ]
df = pd.DataFrame( v, index=i, columns=c )
df

1 号 2 号 3 号 4 号
年龄  53  64  72  82
性别   女   男   男   女

In [51]:
# 转置
df = df.T
df

年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男
4 号  82  女

In [52]:
 # 左右翻转
df = df.iloc[ : , : : -1 ]
df

性别  年龄
1 号  女  53
2 号  男  64
3 号  男  72
4 号  女  82

In [53]:
# 上下翻转
df = df.iloc[ : : -1 , : ]
df

性别  年龄
4 号  女  82
3 号  男  72
2 号  男  64
1 号  女  53

In [54]:
# 数组法创建 sr
i = [ '1 号', '2 号', '3 号', '4 号' ]
v1 = [ 10, 20, 30, 40 ]
v2 = [ '女', '男', '男', '女' ]
v3 = [ 1, 2, 3, 4 ]
sr1 = pd.Series( v1, index=i )
sr2 = pd.Series( v2, index=i )
sr3 = pd.Series( v3, index=i )
sr1, sr2, sr3

(1 号    10
 2 号    20
 3 号    30
 4 号    40
 dtype: int64,
 1 号    女
 2 号    男
 3 号    男
 4 号    女
 dtype: object,
 1 号    1
 2 号    2
 3 号    3
 4 号    4
 dtype: int64)

In [55]:
# 字典法创建 df
df = pd.DataFrame( { '年龄':sr1, '性别':sr2 } )
df

年龄 性别
1 号  10  女
2 号  20  男
3 号  30  男
4 号  40  女

In [56]:
# 把 sr 并入 df 中
df['牌照'] = sr3
df

年龄 性别  牌照
1 号  10  女   1
2 号  20  男   2
3 号  30  男   3
4 号  40  女   4

In [57]:
# 把 df['年龄']分离成 sr4
sr4 = df['年龄']
sr4

1 号    10
2 号    20
3 号    30
4 号    40
Name: 年龄, dtype: int64

In [58]:
# 创建 sr1 和 sr2
v1 = [10, 20, 30, 40]
v2 = [40, 50, 60]
k1 = [ '1 号', '2 号', '3 号', '4 号' ]
k2 = [ '4 号', '5 号', '6 号' ]
sr1 = pd.Series( v1, index= k1 )
sr2 = pd.Series( v2, index= k2 )
sr1, sr2

(1 号    10
 2 号    20
 3 号    30
 4 号    40
 dtype: int64,
 4 号    40
 5 号    50
 6 号    60
 dtype: int64)

In [59]:
# 合并
pd.concat( [sr1, sr2] )

1 号    10
2 号    20
3 号    30
4 号    40
4 号    40
5 号    50
6 号    60
dtype: int64

In [60]:
 # 创建 sr1 与 sr2
v1 = [ 10, 20, 30]
v2 = [ '女', '男', '男']
sr1 = pd.Series( v1, index=[ '1 号', '2 号', '3 号'] )
sr2 = pd.Series( v2, index=[ '1 号', '2 号', '3 号'] )
sr1, sr2

(1 号    10
 2 号    20
 3 号    30
 dtype: int64,
 1 号    女
 2 号    男
 3 号    男
 dtype: object)

In [61]:
# 创建 df
df = pd.DataFrame( { '年龄':sr1, '性别':sr2 } )
df

年龄 性别
1 号  10  女
2 号  20  男
3 号  30  男

In [62]:
# 加上一列
df['牌照'] = [1, 2, 3]
df

年龄 性别  牌照
1 号  10  女   1
2 号  20  男   2
3 号  30  男   3

In [63]:
 # 加上一行
df.loc['4 号'] = [40, '女', 4]
df

年龄 性别  牌照
1 号  10  女   1
2 号  20  男   2
3 号  30  男   3
4 号  40  女   4

In [64]:
# 设定 df1、df2、df3
v1 = [ [10, '女'], [20, '男'], [30, '男'], [40, '女'] ]
v2 = [ [1, '是'], [2, '是'], [3, '是'], [4, '否'] ]
v3 = [ [50, '男', 5, '是'], [60, '女', 6, '是'] ]
i1 = [ '1 号', '2 号', '3 号', '4 号' ]
i2 = [ '1 号', '2 号', '3 号', '4 号' ]
i3 = [ '5 号', '6 号' ]
c1 = [ '年龄', '性别' ]
c2 = [ '牌照', 'ikun' ]
c3 = [ '年龄', '性别', '牌照', 'ikun' ]
df1 = pd.DataFrame( v1, index=i1, columns=c1 )
df2 = pd.DataFrame( v2, index=i2, columns=c2 )
df3 = pd.DataFrame( v3, index=i3, columns=c3 )
df1, df2, df3

(     年龄 性别
 1 号  10  女
 2 号  20  男
 3 号  30  男
 4 号  40  女,
      牌照 ikun
 1 号   1    是
 2 号   2    是
 3 号   3    是
 4 号   4    否,
      年龄 性别  牌照 ikun
 5 号  50  男   5    是
 6 号  60  女   6    是)

In [65]:
# 合并列对象（添加列特征）
df = pd.concat( [df1,df2], axis=1 )
df

年龄 性别  牌照 ikun
1 号  10  女   1    是
2 号  20  男   2    是
3 号  30  男   3    是
4 号  40  女   4    否

In [66]:
# 合并行对象（添加行个体）
df = pd.concat( [df,df3] )
df

年龄 性别  牌照 ikun
1 号  10  女   1    是
2 号  20  男   2    是
3 号  30  男   3    是
4 号  40  女   4    否
5 号  50  男   5    是
6 号  60  女   6    是

In [67]:
# 创建 sr
sr = pd.Series( [ 53, 64, 72 ] , index=['1 号', '2 号', '3 号'] )
sr

1 号    53
2 号    64
3 号    72
dtype: int64

In [68]:
# 创建 df
v = [ [53, '女'], [64, '男'], [72, '男'] ]
df = pd.DataFrame( v, index=[ '1 号', '2 号', '3 号' ], columns=[ '年龄', '性别' ] )
df

年龄 性别
1 号  53  女
2 号  64  男
3 号  72  男

In [69]:
sr = sr + 10
sr

1 号    63
2 号    74
3 号    82
dtype: int64

In [70]:
df['年龄'] = df['年龄'] + 10
df

年龄 性别
1 号  63  女
2 号  74  男
3 号  82  男

In [71]:
sr = sr * 10
sr

1 号    630
2 号    740
3 号    820
dtype: int64

In [72]:
df['年龄'] = df['年龄'] * 10
df

年龄 性别
1 号  630  女
2 号  740  男
3 号  820  男

In [73]:
sr = sr ** 2
sr

1 号    396900
2 号    547600
3 号    672400
dtype: int64

In [74]:
df['年龄'] = df['年龄'] ** 2
df

年龄 性别
1 号  396900  女
2 号  547600  男
3 号  672400  男

In [75]:
# 创建 sr1
v1 = [10, 20, 30, 40]
k1 = [ '1 号', '2 号', '3 号', '4 号' ]
sr1 = pd.Series( v1, index= k1 )
sr1

1 号    10
2 号    20
3 号    30
4 号    40
dtype: int64

In [76]:
# 创建 sr2
v2 = [1, 2, 3 ]
k2 = [ '1 号', '2 号', '3 号' ]
sr2 = pd.Series( v2, index= k2 )
sr2

1 号    1
2 号    2
3 号    3
dtype: int64

In [77]:
sr1 + sr2 # 加法 

1 号    11.0
2 号    22.0
3 号    33.0
4 号     NaN
dtype: float64

In [78]:
sr1 - sr2 # 减法

1 号     9.0
2 号    18.0
3 号    27.0
4 号     NaN
dtype: float64

In [79]:
 sr1 * sr2 # 乘法 

1 号    10.0
2 号    40.0
3 号    90.0
4 号     NaN
dtype: float64

In [80]:
 sr1 / sr2 # 除法


1 号    10.0
2 号    10.0
3 号    10.0
4 号     NaN
dtype: float64

In [81]:
 sr1 ** sr2 # 幂方

1 号       10.0
2 号      400.0
3 号    27000.0
4 号        NaN
dtype: float64

In [82]:
# 设定 df1 和 df2
v1 = [ [10, '女'], [20, '男'], [30, '男'], [40, '女'] ]
v2 = [ 1, 2 ,3, 6 ]
i1 = [ '1 号', '2 号', '3 号', '4 号' ]; c1 = [ '年龄', '性别' ]
i2 = [ '1 号', '2 号', '3 号', '6 号' ]; c2 = [ '牌照' ]
df1 = pd.DataFrame( v1, index=i1, columns=c1 )
df2 = pd.DataFrame( v2, index=i2, columns=c2 )
df1, df2

(     年龄 性别
 1 号  10  女
 2 号  20  男
 3 号  30  男
 4 号  40  女,
      牌照
 1 号   1
 2 号   2
 3 号   3
 6 号   6)

In [83]:
# 加法
df1['加法'] = df1['年龄'] + df2['牌照']
df1

年龄 性别    加法
1 号  10  女  11.0
2 号  20  男  22.0
3 号  30  男  33.0
4 号  40  女   NaN

In [84]:
# 减法、乘法、除法、幂方
df1['减法'] = df1['年龄'] - df2['牌照']
df1['乘法'] = df1['年龄'] * df2['牌照']
df1['除法'] = df1['年龄'] / df2['牌照']
df1['幂方'] = df1['年龄'] ** df2['牌照']

In [85]:
 # 创建 sr
v = [ 53, None, 72, 82 ]
k = ['1 号', '2 号', '3 号', '4 号']
sr = pd.Series( v, index=k )
sr

1 号    53.0
2 号     NaN
3 号    72.0
4 号    82.0
dtype: float64

In [86]:
 # 创建 df
v = [ [None, 1], [64, None], [72, 3], [82, 4] ]
i = [ '1 号', '2 号', '3 号', '4 号' ]
c = [ '年龄', '牌照' ]
df = pd.DataFrame( v, index=i, columns=c )
df

年龄   牌照
1 号   NaN  1.0
2 号  64.0  NaN
3 号  72.0  3.0
4 号  82.0  4.0

In [87]:
# 发现 sr 的缺失值
sr.isnull()

1 号    False
2 号     True
3 号    False
4 号    False
dtype: bool

In [88]:
# 发现 df 的缺失值
df.isnull()

年龄     牌照
1 号   True  False
2 号  False   True
3 号  False  False
4 号  False  False

In [89]:
# 创建 sr
v = [ 53, None, 72, 82 ]
k = ['1 号', '2 号', '3 号', '4 号']
sr = pd.Series( v, index=k )
sr

1 号    53.0
2 号     NaN
3 号    72.0
4 号    82.0
dtype: float64

In [90]:
# 创建 df
v = [ [None, None], [64, None], [72, 3], [82, 4] ]
i = [ '1 号', '2 号', '3 号', '4 号' ]
c = [ '年龄', '牌照' ]
df = pd.DataFrame( v, index=i, columns=c )
df

年龄   牌照
1 号   NaN  NaN
2 号  64.0  NaN
3 号  72.0  3.0
4 号  82.0  4.0

In [91]:
# 剔除 sr 的缺失值
sr.dropna()

1 号    53.0
3 号    72.0
4 号    82.0
dtype: float64

In [92]:
# 剔除 df 含缺失值的行
df.dropna()

年龄   牌照
3 号  72.0  3.0
4 号  82.0  4.0

In [93]:
 # 剔除 df 全是 NaN 的个体
df.dropna(how='all')

年龄   牌照
2 号  64.0  NaN
3 号  72.0  3.0
4 号  82.0  4.0

In [94]:
# 创建 sr
v = [ 53, None, 72, 82 ] 
sr = pd.Series( v, index=['1 号', '2 号', '3 号', '4 号'] )
sr

1 号    53.0
2 号     NaN
3 号    72.0
4 号    82.0
dtype: float64

In [95]:
# 用常数（0）填充
sr.fillna(0)

1 号    53.0
2 号     0.0
3 号    72.0
4 号    82.0
dtype: float64

In [96]:
 # 用常数（均值）填充
import numpy as np
sr.fillna(np.mean(sr))

1 号    53.0
2 号    69.0
3 号    72.0
4 号    82.0
dtype: float64

In [97]:
 # 用前值填充
sr.fillna(method='ffill')

1 号    53.0
2 号    53.0
3 号    72.0
4 号    82.0
dtype: float64

In [98]:
 # 用后值填充
sr.fillna(method='bfill')

1 号    53.0
2 号    72.0
3 号    72.0
4 号    82.0
dtype: float64

In [99]:
 # 设定 df
v = [ [None, None], [64, None], [72, 3], [82, 4] ]
i = [ '1 号', '2 号', '3 号', '4 号' ]; c = [ '年龄', '牌照' ]
df = pd.DataFrame( v, index=i, columns=c )
df

年龄   牌照
1 号   NaN  NaN
2 号  64.0  NaN
3 号  72.0  3.0
4 号  82.0  4.0

In [100]:
 # 用常数（0）填充
df.fillna(0)

年龄   牌照
1 号   0.0  0.0
2 号  64.0  0.0
3 号  72.0  3.0
4 号  82.0  4.0

In [101]:
# 用常数（均值）填充
import numpy as np
df.fillna( np.mean(df) )

年龄    牌照
1 号  45.0  45.0
2 号  64.0  45.0
3 号  72.0   3.0
4 号  82.0   4.0

In [102]:
 # 用前值填充
df.fillna(method='ffill')

年龄   牌照
1 号   NaN  NaN
2 号  64.0  NaN
3 号  72.0  3.0
4 号  82.0  4.0

In [103]:
# 用后值填充
df.fillna(method='bfill')

年龄   牌照
1 号  64.0  3.0
2 号  64.0  3.0
3 号  72.0  3.0
4 号  82.0  4.0

In [104]:
 # 导入 Pandas 对象
df = pd.read_csv('Data.csv', index_col=0)
df

age gender  num kun
1号  10.0      女    1   是
2号  20.0      男    2   是
3号  30.0      男    3   是
4号  40.0      女    4   否
5号  50.0      男    5   是
6号  60.0      女    6   是

In [105]:
# 提取纯数组
arr = df.values
arr

array([[10.0, '女', 1, '是'],
       [20.0, '男', 2, '是'],
       [30.0, '男', 3, '是'],
       [40.0, '女', 4, '否'],
       [50.0, '男', 5, '是'],
       [60.0, '女', 6, '是']], dtype=object)

In [106]:
# 导入 Pandas 对象
df=pd.read_csv('行星数据.csv', index_col=0)

In [107]:
#仅输出前五行
df.head()

发现时间  发现数量   观测方法    行星质量   距地距离     轨道周期
0  1989     1   径向速度  11.680  40.57  83.8880
1  1992     3  脉冲星计时     NaN    NaN  25.2620
2  1992     3  脉冲星计时     NaN    NaN  66.5419
3  1994     3  脉冲星计时     NaN    NaN  98.2114
4  1995     1   径向速度   0.472  15.36   4.2308

In [108]:
#最大值函数 np.max( )
df.max()

发现时间        2014
发现数量           7
观测方法      轨道亮度调制
行星质量        25.0
距地距离      8500.0
轨道周期    730000.0
dtype: object

In [109]:
# 最小值函数 np.min( )
df.min()

发现时间      1989
发现数量         1
观测方法        凌日
行星质量    0.0036
距地距离      1.35
轨道周期    0.0907
dtype: object

In [110]:
# 求和函数 np.sum( )
df.sum()

发现时间                                              2079388
发现数量                                                 1848
观测方法    径向速度脉冲星计时脉冲星计时脉冲星计时径向速度径向速度径向速度径向速度径向速度径向速度径向速...
行星质量                                           1353.37638
距地距离                                            213367.98
轨道周期                                         1986894.2555
dtype: object

In [111]:
# 均值函数 np.mean( )
#df.mean()

In [112]:
# 标准差函数 np.std( )
#df.std()

In [113]:
#查看所有聚合函数信息
df.describe()
#第 1 行 count 是计数项，统计每个特征的有效数量（即排除缺失值），从 count
#可以看出，行星质量的缺失值比较多，需要考虑一定的办法填充或舍弃。
#第 2 行至第 3 行的 mean 与 std 统计每列特征的均值与标准差。
#第 4 行至第 8 行的 min、25%、50%、75%、max 的意思是五个分位点，即
#把数组从小到大排序后，0%、25%、50%、75%、100%五个位置上的数值的取值。
#显然，50%分位点即中位数。

发现时间         发现数量        行星质量         距地距离           轨道周期
count  1035.000000  1035.000000  513.000000   808.000000     992.000000
mean   2009.070531     1.785507    2.638161   264.069282    2002.917596
std       3.972567     1.240976    3.818617   733.116493   26014.728304
min    1989.000000     1.000000    0.003600     1.350000       0.090700
25%    2007.000000     1.000000    0.229000    32.560000       5.442575
50%    2010.000000     1.000000    1.260000    55.250000      39.979500
75%    2012.000000     2.000000    3.040000   178.500000     526.005000
max    2014.000000     7.000000   25.000000  8500.000000  730000.000000

In [114]:
 # 导入 Pandas 对象
df = pd.read_csv('泰坦尼克.csv', index_col=0)
df.head()

性别    年龄 船舱等级       费用  是否生还
0  男  22.0   三等   7.2500     0
1  女  38.0   一等  71.2833     1
2  女  26.0   三等   7.9250     1
3  女  35.0   一等  53.1000     1
4  男  35.0   三等   8.0500     0

In [115]:
# 一个特征：性别
df.pivot_table('是否生还', index='性别')

是否生还
性别          
女   0.742038
男   0.188908

In [116]:
# 两个特征：性别、船舱等级
df.pivot_table('是否生还', index='性别', columns='船舱等级')

船舱等级        一等        三等        二等
性别                                
女     0.968085  0.500000  0.921053
男     0.368852  0.135447  0.157407

In [117]:
# 三个特征：性别、船舱等级、年龄
age = pd.cut( df['年龄'], [0,18,120] ) # 以 18 岁为分水岭
df.pivot_table('是否生还', index= ['性别', age], columns='船舱等级')

船舱等级                一等        三等        二等
性别 年龄                                     
女  (0, 18]    0.909091  0.511628  1.000000
   (18, 120]  0.972973  0.423729  0.900000
男  (0, 18]    0.800000  0.215686  0.600000
   (18, 120]  0.375000  0.133663  0.071429

In [118]:
 # 四个特征：性别、船舱等级、年龄、费用
fare = pd.qcut( df['费用'], 2 ) # 将费用自动分为两部分
df.pivot_table('是否生还', index= ['船舱等级',fare], columns=['性别', age])

性别                             女                   男          
年龄                       (0, 18] (18, 120]   (0, 18] (18, 120]
船舱等级 费用                                                       
一等   (-0.001, 14.454]        NaN       NaN       NaN  0.000000
     (14.454, 512.329]  0.909091  0.972973  0.800000  0.391304
三等   (-0.001, 14.454]   0.714286  0.444444  0.260870  0.125000
     (14.454, 512.329]  0.318182  0.391304  0.178571  0.192308
二等   (-0.001, 14.454]   1.000000  0.880000  0.000000  0.098039
     (14.454, 512.329]  1.000000  0.914286  0.818182  0.030303