In [1]:
import torch
a=torch.tensor([[1,2],[3,4]])
print(torch.reshape(a,(1,-1)))

tensor([[1, 2, 3, 4]])


In [2]:
print(a.reshape(1,-1))
print(a.view(1,-1))

tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3, 4]])
