In [1]:
import torch
a=torch.tensor([[5,6,7],[7,8,9]])
torch.split(a,split_size_or_sections=(1,2),dim=1)#将张量沿着第一维度分割成两份部分

(tensor([[5],
         [7]]),
 tensor([[6, 7],
         [8, 9]]))

In [2]:
torch.split(a,split_size_or_sections=2,dim=1)#将张量沿着第一维度分割成两份部分，按两个元素分割，不足则单列出来

(tensor([[5, 6],
         [7, 8]]),
 tensor([[7],
         [9]]))