In [1]:
import torch
a=torch.Tensor(2)#定义一个形状的张量,含有两个数的一维数组(默认为32位浮点数，与torch.FloatTensor()相同)
print(a)

tensor([0., 0.])


In [2]:
import torch
b=torch.Tensor(1,2)#定义一个形状的张量，生成一个二维数组
print(b)

tensor([[0., 0.]])


In [3]:
import torch
c=torch.Tensor([2])#定义一个指定内容的张量
print(c)

tensor([2.])


In [4]:
import torch
d=torch.Tensor([2,3])#定义一个指定内容的张量
print(d)

tensor([2., 3.])
