In [1]:
import torch
a=torch.Tensor([4])#浮点型张量
print(a.type(torch.IntTensor))#将浮点型张量转为int类型
print(a.type(torch.DoubleTensor))#将浮点型张量转为double类型

tensor([4], dtype=torch.int32)
tensor([4.], dtype=torch.float64)


In [2]:
print(a.int())#数值型特有的方法
print(a.double())

tensor([4], dtype=torch.int32)
tensor([4.], dtype=torch.float64)


In [3]:
print(a.mean())
print(a.sqrt())

tensor(4.)
tensor([2.])
