In [1]:
import torch
a=torch.tensor([[5,6,7],[2,8,0]])
print(torch.t(a))
torch.transpose(a,dim0=1,dim1=0)

tensor([[5, 2],
        [6, 8],
        [7, 0]])


tensor([[5, 2],
        [6, 8],
        [7, 0]])

In [2]:
#另外的方法转职
a.permute(1,0)

tensor([[5, 2],
        [6, 8],
        [7, 0]])