In [1]:
#将cpu中的张量转化到gpu中
import torch
a=torch.FloatTensor([4])
b=a.cuda()
print(b)

tensor([4.], device='cuda:0')


In [2]:
#将gpu的张量搬到cpu上
print(a.cpu())

tensor([4.])


In [3]:
#直接在gpu上定义张量
a=torch.tensor([4],device='cuda')
print(a)

tensor([4], device='cuda:0')


In [4]:
#使用to()指定设备
a=torch.FloatTensor([4])
print(a)
print(a.to('cuda:0'))

tensor([4.])
tensor([4.], device='cuda:0')
