In [1]:
#张量和numpy相互转化

In [2]:
import torch 
import numpy as np
a=torch.Tensor([4])
print(a.numpy())#将张量转化为numpy类型的对象
anp=np.array([4])
print(torch.tensor(anp))#将numpy类型的对象转化为张量
print(torch.from_numpy(anp))#另一种方法

[4.]
tensor([4], dtype=torch.int32)
tensor([4], dtype=torch.int32)


In [3]:
#张量与numpy各自的形状获取
x=torch.randn(2,1)
print(x)
print(x.shape)
print(x.size())
anp=np.asarray({4,2})
print(anp)
print(anp.shape,anp.size)

tensor([[ 0.3944],
        [-1.1805]])
torch.Size([2, 1])
torch.Size([2, 1])
{2, 4}
() 1


In [4]:
#对属性进行改变
print(x.reshape([1,2]).shape)
print(anp.reshape([1,1]).shape)

torch.Size([1, 2])
(1, 1)


In [5]:
#张量与numpy各自的切片
x=torch.rand(2,1)
print(x)
print(x[:])
anp=np.asarray([4,2])
print(anp)
print(anp[:])

tensor([[0.5424],
        [0.8762]])
tensor([[0.5424],
        [0.8762]])
[4 2]
[4 2]


In [6]:
#条件类型切片
print(x[x>0.5])
print(anp[anp>3])

tensor([0.5424, 0.8762])
[4]


In [7]:
#转换numpy会改变张量的值，但改变张量不会改变numpy的值
import torch
import numpy as np
nparray=np.array([1,1])
x=torch.from_numpy(nparray)
print(x)
nparray+=1
print(x)

tensor([1, 1], dtype=torch.int32)
tensor([2, 2], dtype=torch.int32)


In [8]:
#不适用内存替换
nparray=np.array([1,1])
x=torch.from_numpy(nparray)
print(x)
nparray=nparray+1
print(x)

tensor([1, 1], dtype=torch.int32)
tensor([1, 1], dtype=torch.int32)
