In [1]:
import torch
a=torch.FloatTensor([4])
print(a,a+a)

tensor([4.]) tensor([8.])


In [2]:
b=torch.add(a,a)
print(b)

tensor([8.])


In [3]:
torch.add(a,a,out=b)
print(b)

tensor([8.])


In [4]:
#自变化运算函数
a.add_(b)
print(a)

tensor([12.])
